## Example 1. Create a Numpy array of zeros with a desired shap

In [1]:
import numpy as np

In [2]:
np_array_zeroes = np.zeros((3,4)) # 3 rows, 4 columns

In [3]:
np_array_zeroes

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np_array_zeroes.dtype

dtype('float64')

## Example 2. Create a Numpy array of ones

In [5]:
np_array_ones = np.ones((3, 2))

In [6]:
np_array_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

## Example 3. Create a Numpy array of constants


In [7]:
np_array_constants = np.full((2,3), 5)

In [8]:
np_array_constants

array([[5, 5, 5],
       [5, 5, 5]])

## Example 4 a. Create a Numpy array of an Identity matrix

A fundamental array in Linear Algebra is the Identity Matrix. An Identity matrix is a square matrix that has only 1s in its main diagonal and zeros everywhere else. The function np.eye(N) creates a square N x N ndarray corresponding to the Identity matrix. Since all Identity Matrices are square, the np.eye() function only takes a single integer as an argument. Let's see an example:

In [9]:
np_array_identity_matrix = np.eye(5)

In [10]:
np_array_identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
np_array_diogonal_matrix = np.diag([10, 20, 30, 50])

In [12]:
np_array_diogonal_matrix

array([[10,  0,  0,  0],
       [ 0, 20,  0,  0],
       [ 0,  0, 30,  0],
       [ 0,  0,  0, 50]])

## numpy.arange
syntex: numpy.arange([start, ]stop, [step, ]dtype=None)

arange can be called with a varying number of positional arguments:

arange(stop): Values are generated within the half-open interval [0, stop) (in other words, the interval including start but excluding stop).

arange(start, stop): Values are generated within the half-open interval [start, stop).

arange(start, stop, step) Values are generated within the half-open interval [start, stop), with spacing between values given by step

Parameters:
startinteger or real, optional
Start of interval. The interval includes this value. The default start value is 0.

stopinteger or real
End of interval. The interval does not include this value, except in some cases where step is not an integer and floating point round-off affects the length of out.

stepinteger or real, optional
Spacing between values. For any output out, this is the distance between two adjacent values, out[i+1] - out[i]. The default step size is 1. If step is specified as a position argument, start must also be given.

dtypedtype, optional
The type of the output array. If dtype is not given, infer the data type from the other input arguments.

likearray_like, optional
Reference object to allow the creation of arrays which are not NumPy arrays. If an array-like passed in as like supports the __array_function__ protocol, the result will be defined by it. In this case, it ensures the creation of an array object compatible with that passed in via this argument.

New in version 1.20.0.

Returns:
arangendarray
Array of evenly spaced values.

For floating point arguments, the length of the result is ceil((stop - start)/step). Because of floating point overflow, this rule may result in the last element of out being greater than stop.

In [13]:
x = np.arange(10)

In [14]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
x = np.arange(4, 10) # arrange(star_value, stop_value)

In [20]:
x

array([4, 5, 6, 7, 8, 9])

In [23]:
x = np.arange(1, 10, 2)# arrange(star_value, stop_value, step_size)

In [24]:
x

array([1, 3, 5, 7, 9])

In [27]:
x = np.arange(1, 10, .3) #arange allows non-integer setps

In [32]:
x

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## numpy.linspace
Syntax: 
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)


In [28]:
x = np.linspace(0, 10, 3) #linspace(start, stop, num_of_element)

In [29]:
x

array([ 0.,  5., 10.])

In [30]:
x = np.linspace(0, 10, 5)

In [31]:
x

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## Create a Numpy array using linspace(start, stop, n), with stop excluded

In [35]:
x = np.linspace(0, 10, 3, endpoint=False)

In [36]:
x

array([0.        , 3.33333333, 6.66666667])

## numpy.reshape
Syntax: numpy.reshape(array, newshape, order='C')[source]

In [37]:
x = np.arange(20)

In [38]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [39]:
x = np.reshape(x,(4,5))

In [40]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## Example:  Create a Numpy array by calling the reshape() function from the output of arange() function.

In [41]:
y = np.arange(20).reshape(4, 5)

In [42]:
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## Example: Create a rank 2 Numpy array by using the reshape() function

In [47]:
x = np.linspace(0, 50, 10).reshape(5,2)

In [48]:
x

array([[ 0.        ,  5.55555556],
       [11.11111111, 16.66666667],
       [22.22222222, 27.77777778],
       [33.33333333, 38.88888889],
       [44.44444444, 50.        ]])

## Example: Create a Numpy array using the numpy.random.random() function.

In [49]:
x = np.random.random((3,3))

In [50]:
x

array([[0.29655507, 0.44052953, 0.07525951],
       [0.63691629, 0.72420635, 0.12041126],
       [0.97018721, 0.46044724, 0.30605859]])

In [57]:
x = np.random.randint(4, 15, size=(3,2))

In [58]:
x

array([[ 7, 13],
       [ 4,  8],
       [11,  7]])

In [61]:
x = np.random.randint((3,3))

In [62]:
x

array([2, 2])

In [63]:
x = np.random.normal(0, 0.1, size=(100, 100))

In [64]:
x

array([[ 0.0152183 ,  0.03505633,  0.01726908, ...,  0.12044952,
        -0.05706345, -0.0504596 ],
       [ 0.17388105,  0.03160736,  0.098841  , ..., -0.09475795,
         0.09194676, -0.15503237],
       [ 0.06329106, -0.05503617, -0.07196791, ..., -0.0749469 ,
         0.11051454,  0.05561515],
       ...,
       [ 0.06208735, -0.19001879, -0.13383689, ...,  0.07411026,
         0.04963319,  0.00064415],
       [-0.01724813,  0.01123659, -0.12088325, ..., -0.01191609,
        -0.04649114, -0.06430693],
       [-0.05618823,  0.08600494, -0.04914988, ..., -0.03279098,
         0.00807421, -0.18430585]])