## Summary

## Example 1. Access individual elements of 1-D array

In [2]:
import numpy as np

In [4]:
x = np.array([1, 2, 3, 4, 5])

In [9]:
x[0: ]

array([10, 20,  3,  4,  5])

## Example 02: Modify element of 1-D array

In [6]:
x[0: 2]

array([1, 2])

In [7]:
x[0: 2] = 10, 20

In [8]:
x

array([10, 20,  3,  4,  5])

In [11]:
x[0: ] = 100, 200, 300

ValueError: could not broadcast input array from shape (3,) into shape (5,)

In [12]:
x[0: ] = 100, 200, 300, 400, 500

In [13]:
x

array([100, 200, 300, 400, 500])

## Example 3. Access individual elements of 2-D array

In [20]:
x = np.eye(4, 4)

In [21]:
x

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
x[0: ]

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
x[1: 3]

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.]])

## Example 4. Modify an element of 2-D array

In [24]:
x[0, 0] = 10

In [25]:
x

array([[10.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [26]:
x[1, 2] = 20

In [27]:
x

array([[10.,  0.,  0.,  0.],
       [ 0.,  1., 20.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## Example 05: Delete elements 

In [109]:
x = np.array([1, 2, 3, 4, 5])

In [111]:
x = np.delete(x, 0) #syntax: np.delete(array, index)

In [112]:
x

array([3, 4, 5])

In [29]:
x = np.delete(x, [0])

In [30]:
x

array([2, 3, 4, 5])

In [31]:
x = np.delete(x, [0, 2, 3])

In [32]:
x

array([3])

In [34]:
#syntex: np.delete(array,[index])

In [43]:
y = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [44]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
y = np.delete(y, [0, 2], axis=0)

In [42]:
y

array([[4, 5, 6]])

In [45]:
y = np.delete(y, [0, 2], axis=1)

In [46]:
y

array([[2],
       [5],
       [8]])

In [47]:
#axis = 0; row 
#axis = 1; column

## numpy.append
Syntax: numpy.append(array, values, axis=None)

In [48]:
x = np.array([1, 2, 3, 4])

In [51]:
x = np.append(x, 6) #syntax: np.append(array, values)

In [61]:
x

array([1, 2, 3, 4, 6])

In [62]:
x = np.append(x, [10, 11])

In [63]:
x

array([ 1,  2,  3,  4,  6, 10, 11])

In [53]:
y = np.array([[1, 2, 3], [3, 4, 5], [6, 7, 8]])

In [54]:
y = np.append(y, [[7, 8, 9]], axis=0)

In [55]:
y

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8],
       [7, 8, 9]])

In [59]:
q = np.append(y, [[9], [10], [11], [12]], axis=1)

In [60]:
q

array([[ 1,  2,  3,  9],
       [ 3,  4,  5, 10],
       [ 6,  7,  8, 11],
       [ 7,  8,  9, 12]])

## Example 7: Insert elements

In [65]:
# We create a rank 1 ndarray 
x = np.array([1, 2, 5, 6, 7])

# We create a rank 2 ndarray 
y = np.array([[1,2,3],[7,8,9]])

In [66]:
x = np.insert(x, 2, [3,4]) #syntax: np.insert(array, index, values)

In [67]:
x

array([1, 2, 3, 4, 5, 6, 7])

In [68]:
x = np.insert(x, 3, [10, 20])

In [69]:
x

array([ 1,  2,  3, 10, 20,  4,  5,  6,  7])

In [70]:
y

array([[1, 2, 3],
       [7, 8, 9]])

In [71]:
q = np.insert(y,1,[4, 5, 6], axis=0)

In [72]:
q

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
q = np.insert(y,0,[4, 5, 6], axis=0)

In [74]:
q

array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])

In [75]:
#syntex: np.insert(numpy_array, index,[new values], axis)

In [82]:
w = np.insert(y,1, 5, axis=1)

In [83]:
w

array([[1, 5, 2, 3],
       [7, 5, 8, 9]])

In [80]:
y

array([[1, 2, 3],
       [7, 8, 9]])

In [87]:
w = np.insert(y,2, [5,6], axis=1)

In [88]:
w

array([[1, 2, 5, 3],
       [7, 8, 6, 9]])

## numpy.hstack and numpy.vstack
Syntax: 
numpy.hstack(sequence_of_ndarray)
numpy.vstack(sequence_of_ndarray)

In [114]:
# We create a rank 1 ndarray 
x = np.array([1,2])

# We create a rank 2 ndarray 
Y = np.array([[3,4],[5,6]])

In [115]:
x1 = np.array([7, 8])

In [116]:
z = np.vstack((x,Y,x1)) #syntax: np.vstack((array01, array02, ....))

In [117]:
z

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [92]:
x

array([1, 2])

In [95]:
Y

array([[3, 4],
       [5, 6]])

In [94]:
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [96]:
q = np.vstack((Y, x))

In [99]:
q

array([[3, 4],
       [5, 6],
       [1, 2]])

In [100]:
a = np.array([[10, 20], [30, 40]])

In [101]:
q = np.hstack((a, Y)) # must be same dimention 

In [102]:
q

array([[10, 20,  3,  4],
       [30, 40,  5,  6]])

In [103]:
w = np.hstack((Y,x.reshape(2,1)))

In [104]:
w

array([[3, 4, 1],
       [5, 6, 2]])

In [105]:
x

array([1, 2])

In [106]:
Y

array([[3, 4],
       [5, 6]])

In [ ]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

# We create a rank 1 ndarray that will serve as indices to select elements from X
indices = np.array([1,3])

# We print X
print()
print('X = \n', X)
print()

# We print indices
print('indices = ', indices)
print()

# We use the indices ndarray to select the 2nd and 4th row of X
Y = X[indices,:]

# We use the indices ndarray to select the 2nd and 4th column of X
Z = X[:, indices]

# We print Y
print()
print('Y = \n', Y)

# We print Z
print()
print('Z = \n', Z)