## Summary


 ## Example 1. Slicing in a 2-D ndarray

In [2]:
import numpy as np

In [4]:
#create a 4 X 5 ndarray that contains intergers from 0 to 19

x = np.arange(20).reshape(4, 5)

In [5]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [14]:
y = np.arange(9)

In [15]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
y = y.reshape(3,3)

In [21]:
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
y.ndim

2

In [23]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [24]:
# 2-D Array Slice 
z = x[1:4, 2:5] #syntax: array[row_index, column_index]

In [25]:
z

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [29]:
x[1:3, 1:3]

array([[ 6,  7],
       [11, 12]])

In [30]:
x[:, 1:]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

## Example 2. editing elements in a 2-D ndarray

In [31]:
x = np.arange(20).reshape(4, 5)

In [32]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [34]:
x[0,1] = 10

In [36]:
x

array([[ 0, 10,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## Example 3. Demonstrate the copy() function

### numpy.ndarray.copy
Syntax: 
ndarray.copy(order='C')

In [37]:
x = np.arange(20).reshape(4,5)

In [38]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [39]:
w = x[1:4, 2:5].copy()

In [40]:
w

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

## Example 4 a. Use an array as indices to either make slices, select, or change elements

In [3]:
x = np.arange(20).reshape(4,5)

In [5]:
indices = np.array([1, 3]) 


In [7]:
indices

array([1, 3])

In [8]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [43]:
y = x[indices, :]

In [44]:
y

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [45]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [46]:
indices

array([1, 3])

In [47]:
z = x[: , indices]

In [48]:
z

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18]])

## Example 5. Demonstrate the diag() function

In [49]:
x = np.arange(25).reshape(5, 5)

In [50]:
z = np.diag(x) #2-D এরের কোনাকুনি ভ্যালুগুলো এক্সেস করবে

In [51]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
z

array([ 0,  6, 12, 18, 24])

In [53]:
z = np.diag(x, k=1)

In [54]:
z

array([ 1,  7, 13, 19])

In [57]:
z = np.diag(x, k=2)

In [58]:
z

array([ 2,  8, 14])

In [59]:
z = np.diag(x, k=3)

In [60]:
z

array([3, 9])

## Example 6. Demonstrate the unique() function

### numpy.unique
Syntax:
numpy.unique(array, return_index=False, return_inverse=False, return_counts=False, axis=None)
 

In [61]:
x = np.array([[1,2,3],[5,2,8],[1,2,3]])

In [62]:
y = np.unique(x)

In [63]:
y

array([1, 2, 3, 5, 8])