## Example 1. Boolean indexing


In [2]:
import numpy as np

In [3]:
x = np.arange(25).reshape(5, 5)

In [4]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [7]:
print(x[x > 9].reshape(5, 3))

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]]


In [11]:
print(x[(x > 9) & (x < 15)])

[10 11 12 13 14]


## Example 2. Set operations

In [12]:
x = np.array([1, 2, 3, 4, 5])

In [13]:
y = np.array([6, 7, 8, 4, 2])

In [14]:
print(np.intersect1d(x,y))

[2 4]


In [15]:
print(np.union1d(x,y))

[1 2 3 4 5 6 7 8]


In [16]:
print(np.setdiff1d(x,y))

[1 3 5]


## numpy.ndarray.sort method
Syntax: ndarray.sort(axis=1, kind=none, order=None)

## Example 3. Sort arrays using sort() function

In [17]:
x = np.random.randint(1, 11, size=(10,))

In [18]:
x

array([6, 4, 1, 7, 5, 6, 2, 1, 7, 1])

In [19]:
np.sort(x)

array([1, 1, 1, 2, 4, 5, 6, 6, 7, 7])

In [21]:
np.unique(x) # unique function --> sort value and find unique value

array([1, 2, 4, 5, 6, 7])

## Example 4. Sort rank-2 arrays by specific axis

In [22]:
x = np.random.randint(1,11, size=(5,5))

In [23]:
x

array([[ 6,  7,  5,  5, 10],
       [ 4,  3,  9,  8,  3],
       [ 7,  6,  9,  9,  6],
       [ 4,  5,  3,  5,  4],
       [ 2, 10,  7,  4,  1]])

In [24]:
np.sort(x, axis=1)

array([[ 5,  5,  6,  7, 10],
       [ 3,  3,  4,  8,  9],
       [ 6,  6,  7,  9,  9],
       [ 3,  4,  4,  5,  5],
       [ 1,  2,  4,  7, 10]])

In [25]:
np.sort(x, axis=0)

array([[ 2,  3,  3,  4,  1],
       [ 4,  5,  5,  5,  3],
       [ 4,  6,  7,  5,  4],
       [ 6,  7,  9,  8,  6],
       [ 7, 10,  9,  9, 10]])