## Example 1. Element-wise arithmetic operations on 1-D arrays

In [2]:
import numpy as np

In [3]:
x = np.array([1, 2, 3, 4])
y = np.array([5.5, 6.5, 7.5, 8.5])

In [4]:
print('x + y = ', x + y)
print('add(x,y) = ', np.add(x,y))

x + y =  [ 6.5  8.5 10.5 12.5]
add(x,y) =  [ 6.5  8.5 10.5 12.5]


In [5]:
print('x - y = ', x - y)
print('subtract(x,y) = ', np.subtract(x,y))

x - y =  [-4.5 -4.5 -4.5 -4.5]
subtract(x,y) =  [-4.5 -4.5 -4.5 -4.5]


In [7]:
print('x * y = ', x * y)
print('multiply(x,y) = ', np.multiply(x,y))

x * y =  [ 5.5 13.  22.5 34. ]
multiply(x,y) =  [ 5.5 13.  22.5 34. ]


In [8]:
print('x / y = ', x / y)
print('divide(x,y) = ', np.divide(x,y))

x / y =  [0.18181818 0.30769231 0.4        0.47058824]
divide(x,y) =  [0.18181818 0.30769231 0.4        0.47058824]


## Example 2. Element-wise arithmetic operations on a 2-D array (Same shape)

In [9]:
x = np.array([1, 2, 3, 4]).reshape(2, 2)
y = np.array([5.5, 6.5, 7.5, 8.5]).reshape(2,2)

In [10]:
x

array([[1, 2],
       [3, 4]])

In [11]:
y

array([[5.5, 6.5],
       [7.5, 8.5]])

In [12]:
print('x + y = ', x + y)
print('add(x,y) = ', np.add(x,y))

x + y =  [[ 6.5  8.5]
 [10.5 12.5]]
add(x,y) =  [[ 6.5  8.5]
 [10.5 12.5]]


In [13]:
print('x - y = ', x - y)
print('subtract(x,y) = ', np.subtract(x,y))

x - y =  [[-4.5 -4.5]
 [-4.5 -4.5]]
subtract(x,y) =  [[-4.5 -4.5]
 [-4.5 -4.5]]


In [14]:
print('x * y = ', x * y)
print('multiply(x,y) = ', np.multiply(x,y))

x * y =  [[ 5.5 13. ]
 [22.5 34. ]]
multiply(x,y) =  [[ 5.5 13. ]
 [22.5 34. ]]


In [15]:
print('x / y = ', x / y)
print('divide(x,y) = ', np.divide(x,y))

x / y =  [[0.18181818 0.30769231]
 [0.4        0.47058824]]
divide(x,y) =  [[0.18181818 0.30769231]
 [0.4        0.47058824]]


## Example 3. Additional mathematical functions

In [16]:
x = np.array([1, 2, 3, 4])

In [17]:
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [18]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [19]:
np.power(x, 2)

array([ 1,  4,  9, 16])

## Example 4. Statistical functions

In [29]:
X = np.array([[1, 2], [3, 4]])

In [30]:
X

array([[1, 2],
       [3, 4]])

In [31]:
X.mean()

2.5

In [32]:
print('Average of all elements in the columns of X:', x.mean(axis=0))
print('Average of all elements in the rows of X:', x.mean(axis=1))

Average of all elements in the columns of X: [2. 3.]
Average of all elements in the rows of X: [1.5 3.5]


In [33]:
X.sum()

10

In [34]:
print()
print('Sum of all elements in X:', X.sum())
print('Sum of all elements in the columns of X:', X.sum(axis=0))
print('Sum of all elements in the rows of X:', X.sum(axis=1))
print()
print('Standard Deviation of all elements in X:', X.std())
print('Standard Deviation of all elements in the columns of X:', X.std(axis=0))
print('Standard Deviation of all elements in the rows of X:', X.std(axis=1))
print()
print('Median of all elements in X:', np.median(X))
print('Median of all elements in the columns of X:', np.median(X,axis=0))
print('Median of all elements in the rows of X:', np.median(X,axis=1))
print()
print('Maximum value of all elements in X:', X.max())
print('Maximum value of all elements in the columns of X:', X.max(axis=0))
print('Maximum value of all elements in the rows of X:', X.max(axis=1))
print()
print('Minimum value of all elements in X:', X.min())
print('Minimum value of all elements in the columns of X:', X.min(axis=0))
print('Minimum value of all elements in the rows of X:', X.min(axis=1))


Sum of all elements in X: 10
Sum of all elements in the columns of X: [4 6]
Sum of all elements in the rows of X: [3 7]

Standard Deviation of all elements in X: 1.118033988749895
Standard Deviation of all elements in the columns of X: [1. 1.]
Standard Deviation of all elements in the rows of X: [0.5 0.5]

Median of all elements in X: 2.5
Median of all elements in the columns of X: [2. 3.]
Median of all elements in the rows of X: [1.5 3.5]

Maximum value of all elements in X: 4
Maximum value of all elements in the columns of X: [3 4]
Maximum value of all elements in the rows of X: [2 4]

Minimum value of all elements in X: 1
Minimum value of all elements in the columns of X: [1 2]
Minimum value of all elements in the rows of X: [1 3]


## Example 5. Change value of all elements of an array

In [37]:
x = np.array([[1,2], [3,4]])

In [38]:
x

array([[1, 2],
       [3, 4]])

In [36]:
3 * x

array([[ 3,  6],
       [ 9, 12]])

In [39]:
3+x

array([[4, 5],
       [6, 7]])

In [40]:
x - 3

array([[-2, -1],
       [ 0,  1]])

In [42]:
x/3

array([[0.33333333, 0.66666667],
       [1.        , 1.33333333]])

## Example 6. Arithmetic operations on 2-D arrays (Compatible shape)

In [43]:
x = np.array([1, 2, 3])

In [44]:
y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [46]:
z = np.array([1, 2, 3]).reshape(3,1)

In [47]:
x

array([1, 2, 3])

In [48]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
z

array([[1],
       [2],
       [3]])

In [50]:
x + y

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [51]:
x+z

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])