In [1]:
import numpy as np

In [3]:
np_array = np.array([1, 2, 3, 4, 5])

In [4]:
print('np_array = ', np_array)

np_array =  [1 2 3 4 5]


In [5]:
np_array.ndim

1

In [6]:
np_arr_2D = np.array([[1, 2, 3], [4, 5, 6], [10, 11, 12]])

In [7]:
np_arr_2D

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12]])

In [8]:
np_arr_2D.ndim

2

In [9]:
np_arr_3D = np.zeros((2, 3, 4))

In [10]:
np_arr_3D

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [11]:
np_arr_2D.shape

(3, 3)

In [12]:
np_array.shape

(5,)

In [13]:
np_arr_3D.shape

(2, 3, 4)

In [14]:
np_arr_2D.dtype

dtype('int64')

In [15]:
np_array.dtype

dtype('int64')

In [20]:
np_array_type = np.array([1, 2, 3, True])

In [21]:
np_array_type.dtype

dtype('int64')

In [22]:
np_array_type = np.array([1, 2, 3, True, "Emdadul"])

In [23]:
np_array_type.dtype

dtype('<U21')

In [24]:
np_array_type = np.array([1, 2, 3, True, "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"])

In [25]:
np_array_type.dtype

dtype('<U36')

In [26]:
np_array_float = np.array([2.0, 3.3, 2.1])

In [27]:
np_array_float.dtype

dtype('float64')

In [28]:
np_array_mixed = np.array([1, 2.4, 3.5, 4])

In [29]:
np_array_mixed.dtype

dtype('float64')

We can see that when we create an ndarray with only floats, NumPy stores the elements in memory as 64-bit floating point numbers (float64). However, notice that when we create an ndarray with both floats and integers, as we did with the np_array_mixed ndarray above, NumPy assigns its elements a float64 dtype as well. This is called upcasting. Since all the elements of an ndarray must be of the same type, in this case NumPy upcasts the integers in np_array_mixed to floats in order to avoid losing precision in numerical computations

### Using a 1-D Array of Float, and specifying the datatype of each element as int64

In [30]:
np_array = np.array([1.5, 2.2, 2.7, 3.2], dtype='int64')

In [31]:
np_array

array([1, 2, 2, 3])

## Save the NumPy array to a File

Once you create an ndarray, you may want to save it to a file to be read later or to be used by another program. NumPy provides a way to save the arrays into files for later use - let's see how this is done

In [32]:
np_array = np.array([1, 2, 3, 4, 5])

In [33]:
np.save('numpy_array', np_array)

## Read Numpy Array from save file

In [34]:
np_array_load = np.load('numpy_array.npy')

In [35]:
np_array_load

array([1, 2, 3, 4, 5])